### ISSUE TITLE
➕ [ADD] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by jane1choi** [30th-THE-SOPT-iOS-Part/ChoiEunJu#1]
## 🍎 이슈 요약
- 프로젝트 초기 세팅

## ✅ 체크 리스트

- [x] 프로젝트 파일 추가
- [x] pod 설치
- [x] 폴더링
- [x] extensions 파일 추가

**Comment by hwangJi-dev** [comment]
나도선배를 향한 사랑 잘 보고 갑니다 ~ 두눈 뜨고 지켜보겠어요 ~ 👀 하나 둘 셋 최은주 화이팅 !

**Comment by jane1choi** [comment]
> 나도선배를 향한 사랑 잘 보고 갑니다 ~ 두눈 뜨고 지켜보겠어요 ~ 👀 하나 둘 셋 최은주 화이팅 !

하나 둘 셋 황지은 사랑해~
